sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eO4j7ZSvz/DP3Qnv/iFhJ5MYwIgPxXrXLG7p/UWmaB1eyYmP71M218KTgO1yVt6THTwdZIj/mbKMhbnBgO8TjI6JhlaU50jioXK6uMsE+xqH8WLy+V34pwFvqQzWW+OaH42OBv0DvZDmY2HCKXwXeGtJxpuvX7WenQYZd0+5S3MRZVHzW4SSc5gWQeyXXLQKxLJMpZj7q7Q5YXoYBxaseD08oWdTbjLECjvXap56O3Cf9WySUOEAioFvsfpJYMAXliRtBO1Q9NSPILH3DBrqhCOuxkg0Urlie7PSoZJyRhRTLQ6aN9+8138/c9Bc10W3uGG/94dH696raZIBOVSMqUhLcNfpcMK+06fAKcFG71lBRnQWPoqcA+9fI9vHAvMkPR0C5eXkAF2vbxWSEYMI2jnl/lKsVqEDxOQGWqvsVAit5olyrzGcu2o6O7YCG4UKoA8hb5N6t92YIh0MX+SNJB7tA/xPO4Z1AzWtHdcvYaYsbsfWrygyyhu8huPbx2YOH7Zb4THFVfTJWaxtzKKr1R3TR6CIqhmSa5NAKNHxYnp1RpqVa57pwPsoOoHjoTJjfyhCYibMD6jRjWkcagvYjudIvXJYWa6Qe0hLg7TVBX0fLSM8zgnQumXR6bBXM+UckVoUjgDFDKqeMuLAopazcFiWzwElVxdl0HT56b5JQBQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Drums-of-Jeopardy_1913
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy